import type { NextPage } from "next";
import Head from "next/head";
import CharacterCard from "../components/CharacterCard";
import RandomCharacter from "../components/RandomCharacter";
import useCharacters from "../hooks/useCharacters";

const Home: NextPage = () => {
  const { characters } = useCharacters();

  return (
    <div>
      <Head>
        <title>Home | Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <RandomCharacter />
        <style jsx>{`
          main {
            margin-top: 1rem;
          }
        `}</style>
      </main>
      <section className="characters">
        <div className="characters__box container">
          {characters &&
            characters.map((i) => <CharacterCard character={i} key={i.id} />)}
        </div>
        <style jsx>{`
          .characters {
            margin-top: 1rem;
          }

          @media (min-width: 500px) {
            .characters__box {
              display: grid;
              grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
            }
          }
        `}</style>
      </section>
      <footer>
        <div className="container">
          <p className="author">
            Joaquín Buendía
            <span>@jbuendia1y</span>
          </p>
        </div>
        <style jsx>{`
          .author {
            text-align: center;
          }
        `}</style>
      </footer>
    </div>
  );
};

export default Home;
