import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { CharacterFilter } from "rickmortyapi/dist/interfaces";
import CharacterCard from "../components/CharacterCard";
import Paginate from "../components/Paginate";
import RandomCharacter from "../components/RandomCharacter";
import useCharacters from "../hooks/useCharacters";

const Home: NextPage = () => {
  const [filter, setFilter] = useState<CharacterFilter>();
  const { characters, totalPages, currentPage } = useCharacters(filter);

  const changePage = (page: number) => {
    setFilter((v) => ({ ...v, page }));
  };

  return (
    <div>
      <Head>
        <title>Home | Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <RandomCharacter />
        <style jsx>{`
          main {
            margin-top: 1rem;
          }
        `}</style>
      </main>
      <section className="characters">
        <div className="characters__box container">
          {characters &&
            characters.map((i) => <CharacterCard character={i} key={i.id} />)}
          <div className="paginate">
            <Paginate
              OnChange={changePage}
              totalPages={totalPages}
              currentPage={currentPage}
            />
          </div>
        </div>
        <style jsx>{`
          .characters {
            margin-top: 1rem;
          }

          .paginate {
            margin: 0 auto;
            max-width: 100%;
            width: 100%;
          }

          @media (min-width: 500px) {
            .characters__box {
              display: grid;
              grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
            }
            .paginate {
              grid-column: 1/-1;
            }
          }
        `}</style>
      </section>
      <footer>
        <div className="container">
          <p className="author">
            Joaquín Buendía
            <span>@jbuendia1y</span>
          </p>
        </div>
        <style jsx>{`
          .author {
            text-align: center;
          }
        `}</style>
      </footer>
    </div>
  );
};

export default Home;
